# Setup
title:            'The Costly Effects of an Outdated Organ Donation System'
tagline:          ''
description:      'This is the description'
production_url:   'https://bloomworks.digital/organdonationreform'
url:              'http://localhost:4000'

author:
  name:           'Author'
  url:            https://github.com/CTOpenData/data-sharing-playbook

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Bloom-Works/organ-donation-reform

# Google Analytics
google_analytics: UA-XXXXXXXXXX-X

plugins:
  - jekyll-toc

toc:
  min_level: 2 # default: 1
  max_level: 2 # default: 6
